name = 'prod'
url = "https://www.goetzsurveys.com"
#url = "localhost"
languageCode = "en-us"
theme = "hugo-universal-theme"
#SEO
canonifyURLs = true
uglyURLs = false
enableRobotsTXT = true

hero_image = "/images/boundary-forest.jpg"
hero_alt = "Surveying Boundary in the forest"


#themesDir = "../.."
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"

# number of words of summarized post content (default 70)
summaryLength = 70

# not pluralize title pages by default
pluralizelisttitles = false


# Define the number of posts per page
[pagination]
    pagerSize = 10

# Main menu
[menu]

[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 2

[[menu.main]]
    name       = "Services"
    identifier = "menu.services"
    url        = "/"
    weight     = 2

[[menu.main]]
    name       = "Boundary Surveys"
    url        = "/services/boundary"
    weight     = 1
    parent     = "menu.services"

[[menu.main]]
    name       = "Topographic Mapping"
    url        = "/services/topographic-mapping"
    weight     = 2
    parent     = "menu.services"

[[menu.main]]
    name       = "Construction Staking"
    url        = "/services/construction-staking"
    weight     = 3
    parent     = "menu.services"


[[menu.main]]
    name       = "About Us"
    identifier = "menu.about"
    url        = "/about"
    weight     = 4

[[menu.main]]
    name       = "FAQ"
    identifier = "menu.faq"
    url        = "/faq/"
    weight     = 6

[[menu.main]]
    identifier = "contact"
    name       = "Contact"
    url        = "/contact/"
    weight     = 7


[params]


    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    enableGoogleMaps = true
    googleMapsApiKey = "AIzaSyCPWJE_F15xnOuPZDGwf1LLBBsVhuCRGRY"

    latitude = "36.959526368931606"
    longitude = "-122.03832086817008"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 50 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - register your account to https://formspree.io/register
    # - login and create new form
    # - set your form's endpoint url under 'formspree_action' below
    # - upload the generated site to your server
    # - test a dummy email yourself
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io endpoint url
    formspree_action = "https://formspree.io/f/mdaogowd"
    contact_form_ajax = false

    # Formspree form supports Google reCAPTCHA Key (type v2).
    # If you use this feature, you should enable reCAPTCHA feature in the Formspree dashboard.
    #
    # By default, Formspree use a redirect page for recaptcha widget.
    # If you use a recaptcha widget in your contact page, you should do next steps.
    # (if you don't want, skip these steps)
    #
    #   1. register your site on Google recaptcha admin page: https://www.google.com/recaptcha/admin
    #   2. select reCAPTCHA v2 and checkbox widget type.
    #   3. remember site key and secret key.
    #   4. enter secret key into "Custom reCAPTCHA Key" field in your Formspree form setting page.
    #   5. change `enableRecaptchaInContactForm` is to true
    #   6. enter site key into `googleRecaptchaKey` to enable a recaptcha widget in your page.
    #
    enableRecaptchaInContactForm = false
    googleRecaptchaKey = "site_key_for_google_recaptcha"

    about_us = "<p>Providing quality land surveying services to the Santa Cruz area.</p>"
    copyright = "Copyright (c) 2026, Goetz Surveys; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    dropdown_mouse_over = false

    disabled_logo = false
    logo_text = "Goetz Surveys"

    logo = "images/logo.png"
    logo_small = "images/logo-small.png"
    contact_url = "/contact"
    address = """<p class="text-uppercase"><strong>Goetz Surveys</strong>
        <br>(831) 295-5523
        <br>office@goetzsurveys.com
        <br>
        <br>
        <br>
        <strong>Santa Cruz</strong>
      </p>
      """

  description = "Professional land surveying services specializing in boundary surveys, topographic mapping, and construction staking throughout California."
  
[permalinks]

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.features]
    enable = true
    cols = 3 # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more information take a look at the README.

[taxonomies]
    category = "categories"
    tag = "tags"
    author = "authors"
